change .s2i

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,32 +1,32 @@
-#!/bin/bash -e
-#
-# S2I assemble script for the 'tomcat8-jre8' image.
-# The 'assemble' script builds your application source so that it is ready to run.
-#
-# For more information refer to the documentation:
-#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
-#
+# source code provided to S2I
+LOCAL_SOURCE_DIR=$HOME
 
-if [[ "$1" == "-h" ]]; then
-	# If the 'tomcat8-jre8' assemble script is executed with '-h' flag,
-	# print the usage.
-	exec /usr/libexec/s2i/usage
+# deploy WAR files at /usr/local/tomcat/webapps
+DEPLOY_DIR=/usr/local/tomcat/webapps
+
+cp -Rf /opt/s2i/destination/src/. $LOCAL_SOURCE_DIR
+
+chgrp -R 0 $LOCAL_SOURCE_DIR
+chmod -R g+rw $LOCAL_SOURCE_DIR
+
+if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+	pushd $LOCAL_SOURCE_DIR &> /dev/null
+
+	export MAVEN_ARGS="package -Dmaven.test.skip=true "
+	echo "----------------------Starting build apps war files..."
+	mvn -version
+	mvn $MAVEN_ARGS
+
+	ERR=$?
+	if [ $ERR -ne 0 ]; then
+		echo "-------------------Aborting due to error code $ERR from mvn package"
+		exit $ERR
+	fi
+
+	echo "--------------Copying build war files into $DEPLOY_DIR for latet deployment"
+	cp /opt/app-root/src/hcpaas-web-ui/target/hcpaas-web-ui.war $DEPLOY_DIR/ROOT.war
 fi
 
-# Restore artifacts from the previous build (if they exist).
-#
-if [ "$(ls /tmp/artifacts/ 2>/dev/null)" ]; then
-  echo "---> Restoring build artifacts..."
-  mv /tmp/artifacts/. ./
-fi
-
-# copy source code to compilation
-echo "---> Copy source code..."
-#cp -Rf /tmp/src/. ./
+echo "...done"
 
 
-echo "---> Building application from source..."
-# TODO: Add build steps for your application, eg npm install, bundle install
-
-echo "---> Installing application source..."
-#cp -Rf /tmp/src/. ./
